### ISSUE TITLE
Add SparseRegularInverse::info()

### ISSUE THREAD

**Issue by Spammed** [yixuan/spectra#111]
Thank you for your implementation, I use it with great success and satisfaction.

I use SparseRegularInverse as an alternative to SparseCholesky via a template parameter, so I like it when both have the same interface.

I was missing SparseRegularInverse::info(), but it was easy to retrofit.

Noticing the current activity on the code so I thought maybe I should bring this little thing up. Because unfortunately lagging  a own github repository set up, the patch is just copied here.

```
---
 include/Spectra/MatOp/SparseRegularInverse.h | 10 ++++++++++
 1 file changed, 10 insertions(+)

diff --git a/include/Spectra/MatOp/SparseRegularInverse.h b/include/Spectra/MatOp/SparseRegularInverse.h
index 3abd0c1..dcfaec5 100644
--- a/include/Spectra/MatOp/SparseRegularInverse.h
+++ b/include/Spectra/MatOp/SparseRegularInverse.h
@@ -39,6 +39,7 @@ private:
     ConstGenericSparseMatrix m_mat;
     const int m_n;
     Eigen::ConjugateGradient<SparseMatrix> m_cg;
+	int m_info;  // status of the decomposition
 
 public:
     ///
@@ -55,6 +56,9 @@ public:
             throw std::invalid_argument("SparseRegularInverse: matrix must be square");
 
         m_cg.compute(mat);
+		m_info = (m_cg.info() == Eigen::Success) ?
+			SUCCESSFUL :
+			NUMERICAL_ISSUE;
     }
 
     ///
@@ -66,6 +70,12 @@ public:
     ///
     Index cols() const { return m_n; }
 
+	///
+	/// Returns the status of the computation.
+	/// The full list of enumeration values can be found in \ref Enumerations.
+	///
+	int info() const { return m_info; }
+
     ///
     /// Perform the solving operation \f$y=B^{-1}x\f$.
     ///
-- 
2.27.0.windows.1

```

**Comment by yixuan** [comment]
Hi @Spammed, thanks for the suggestion and the patch. In fact I had thought about including the `info()` function, but didn't do that due to the following reason. `Eigen::ConjugateGradient` is an iterative linear solver, whose `compute()` member function doesn't do any actual decomposition, so `m_cg.info()` is almost always "success" after calling `compute()`. The real computation and convergence test happen in the `solve()` member function.

But I get your point that adding an `info()` function makes the template programming easier, so I have made [this change](https://github.com/yixuan/spectra/commit/c0e35c25cad2a803f3206ea1e94b75bbb45f3e19), by adding both the `info()` member function and the convergence test in `solve()`.

Note that I worked in the [1.y.z](https://github.com/yixuan/spectra/tree/1.y.z) branch, which will be the next major release. It breaks a lot of APIs, so you may need to change your code accordingly. Also see the [discussion](https://github.com/yixuan/spectra/issues/92) here.

**Comment by Spammed** [comment]
Thanks for considering the idea and even greater thanks for the continued work on Spectra.

I am a friend of API refactoring in general and I am excited about it.
Let's see how much 'trouble' it will cause me to be able to use the improvements in the new version.

**Comment by yixuan** [comment]
Great! The [test file](https://github.com/yixuan/spectra/blob/1.y.z/test/SymGEigsRegInv.cpp) should give you some ideas about how to change the code.
