### ISSUE TITLE
Decomposition precision [not urgent]

### ISSUE THREAD

**Issue by jdbancal** [yixuan/spectra#13]
Hi @yixuan,

I have two questions regarding the precision of the eigenvalue/eigenvector computation in Spectra : I see that the code has a variable called `m_prec` (e.g. on line of GenEgsSolver.h), so I'm wondering

 - What is the difference between this variable and the tolerance `tol` (second argument of the function `compute`)? What should we expect when tol is larger than m_prec? What should we expect when tol is smaller than m_prec?

 - Second, why is the variable `m_prec` set to eps^(2/3) where `eps` is the precision of the Scalar type? In presence of doubles, this looks like it only guarantees 10 digits of precision, whereas doubles can in principle have ~15 digits of precision. Is the algorithm only stable for up to 10 digits of precision? Or is there another specific reason for that?

**Comment by yixuan** [comment]
Hi @jdbancal,

For your first question, `tol` is indeed the tolerance threshold for convergence, and `m_prec` can be regarded as a number that is "approximately zero". `m_prec` is used internally in the following scenarios:

- To judge whether an eigenvalue is complex or real. This is because the general eigen solver will return all eigenvalues as complex numbers, but usually there exist some real ones, and I use `m_prec` to filter them out.
- To test orthogonality of vectors. When constructing an orthogonal basis of some linear space, the numerical orthogonality gradually breaks down as iterations go on. The algorithm will correct the orthogonality if its value goes beyond `m_prec`.
- In convergence test, `tol` is the relative tolerance, and `tol * m_prec` is the absolute tolerance, so actually the criterion is pretty stringent.

As for the value of `m_prec`, it was taken directly from ARPACK, and I don't have a very strong reason why it is this specific number. I guess the rationale is that `m_prec` should be of larger magnitude than `eps`, for example the complex eigenvalues roughly have precision of similar order as `eps`, and hence we need a looser threshold to filter out the real ones.

**Comment by jdbancal** [comment]
Thanks for your update on the source code regarding epsilons!
The precision of the eigenvalue decompositions is better now

**Comment by yixuan** [comment]
Thanks for the testing. Let me first close this issue, and you can reopen it once you encounter any more in the future.
