### ISSUE TITLE
syntax seems a little odd

### ISSUE THREAD

**Issue by cfwen** [yixuan/spectra#25]
I am looking for a sparse eigen solver based on Eigen, spectra does the job. However I found the usage is a little odd to me, instead of following syntax
```
DenseSymMatProd<double> op(M);
// Construct eigen solver object, requesting the largest three eigenvalues
SymEigsSolver< double, LARGEST_ALGE, DenseSymMatProd<double> > eigs(&op, 3, 6);
eigs.init();
eigs.compute();
VectorXd ses.eigenvalues();
MatrixXd ses.eigenvectors();
```
can we simplify above to
```
SymEigsSolver<MatrixXd> ses(A, LARGEST_ALGE, 3); // compute largest three eigenvalues
VectorXd ses.eigenvalues();
MatrixXd ses.eigenvectors();
```
like how Eigen::SelfAdjointEigenSolver does?

**Comment by yixuan** [comment]
Hi @cfwen, usually the API is subject to personal flavors, but I do have some reasons to make it the way you see now.
1. One key idea of Spectra is to use a matrix **operator**, rather than a concrete matrix, as the input of solver. Therefore, `Eigen::MatrixXd` needs to be converted to an operator first.
2. The selection rule, e.g., `LARGEST_ALGE`, is one template parameter, since it avoids some run-time switch branches. But this can be made into a run-time option anyway.
3. The `init()` method has an overloaded version to let you provide the initial starting vector.
4. The `Eigen::SelfAdjointEigenSolver` class also has a `compute()` method, and one version of its constructor simply calls `compute()`. However in Spectra, the `compute()` function contains several parameters, so it will be messy if I forward everything to the constructor of `SymEigsSolver`.

That said, there is still a possibility that Spectra may change its API in the future. In fact, we are considering to integrate Spectra into Eigen, and there was a discussion on the API design: https://listengine.tuxfamily.org/lists.tuxfamily.org/eigen/2017/02/msg00023.html. Feel free to post to that mailing list to give your opinion.

**Comment by cfwen** [comment]
Thanks for your reply @yixuan . 

In fact what confused me most is the matrix operator. It seems to just take a matrix as input, then the operator used as input to EigenSolver. Inside the matrix operator constructor, nothing serious happened. So what role does the matrix operator play during the process?

**Comment by yixuan** [comment]
For dense matrices, yes, the operator is nothing but a direct call to the matrix-vector product, but for sparse matrices, you may have some specialized algorithms that are faster than the generic `SparseMatrix` implementation, and this is when you can define your own matrix operator to achieve better performance. See the last example in the README file.

**Comment by cfwen** [comment]
now I get it 👍
