### ISSUE TITLE
How to define set_shift() in user supplied op class?

### ISSUE THREAD

**Issue by ZhuonanLin** [yixuan/spectra#34]
@yixuan. Hi, first thanks for your work on the spectra library, this makes me move from out-of-date ARPACK++ to your package.
I have a question for user-supplied matrix-vector multiplication case. I wonder how I should define the set_shift(sigma) function in Mymatrix class. What kind of transformation/information should I provide to implement the  user-supplied shift-and-invert mode? I'm considering a standard problem with B = Identity Matrix.
Thank you in advance.

**Comment by yixuan** [comment]
Hi Zhuonan,

There is no real requirement for the implementation of the `set_shift()` function. It is mainly used to store some information about the shift parameter `sigma`. What is really needed is to write the `perform_op()` function that computes `inv(A - sigma * I) * x`.

Therefore, a trivial implementation of `set_shift()` is to store the `sigma` parameter to a private variable, so that in `perform_op()` you have access to the value of `sigma`.

**Comment by ZhuonanLin** [comment]
Hi yixuan, thanks for your reply. In my case, I deal with the dense matrix so that the explicit inversion of (A - sigma * I) is not available.  I'm trying to solve linear system (A - sigma * I) * y = x, Instead of inv(A - sigma * I) * x = y.  To do this, I'm using reverse communication interface in ARPACK++ to solve this. However, a problem is the the eigenvalues this method got is always the same to shift sigma. I'm figuring out why. Do you have any experience? Thanks!

**Comment by yixuan** [comment]
What I described was exactly the method you used: factorize `A - sigma * I` and solve the linear equation. If you are dealing with dense matrices, I think the [DenseSymShiftSolve](https://spectralib.org/doc/classspectra_1_1densesymshiftsolve) class already defines the operator you need. See the example in https://spectralib.org/doc/classspectra_1_1symeigsshiftsolver.

Not sure what you meant by saying "the same to shift sigma". Could you elaborate?

**Comment by yixuan** [comment]
If there is no further questions, I'll close it first.
