### ISSUE TITLE
SymGEigsSolver fails on a (large ?) system

### ISSUE THREAD

**Issue by cedhub** [yixuan/spectra#51]
Hi Yihuan !

I'm interested in solving a generalized eigenvalue problem for Finite Element Method.
If the solver works well on small systems, it fails to extract the eigenvalues on a large sparse system (~70k x 70k).

I was wondering if I'm doing something wrong somewhere.
I attach my test file (main.cpp) and matrices (CantileverClamped_[k|m]Matrix.txt):

https://www.dropbox.com/s/tnshw4yh4y98trr/Archive.zip?dl=0

Would you (or someone else who reads this post) have some time to test it and give me a feedback ?

Thanks in advance !
Cédric

**Comment by yixuan** [comment]
I was able to get the largest eigenvalues of this system in tens of seconds, but saw very slow convergence for the smallest ones. This is also expected since largest ones are much faster to converge.

I changed the `ncv` parameter to 50 in the constructor, and the solver converged at iteration 304, with the following output:
```
4659.39  4064.8 3539.79 2562.45 2510.54 1703.19 1175.99 972.458 315.557 162.213
```

**Comment by yixuan** [comment]
I had similar timing, but without compiling with OpenMP. In fact the algorithm is mostly sequential, so OpenMP doesn't help much.
