### ISSUE TITLE
Error in example: "And here is an example for user-supplied matrix operation class."

### ISSUE THREAD

**Issue by linuxfreebird** [yixuan/spectra#60]
I tried compiling the last example mentioned in https://spectralib.org/quick-start.html titled "And here is an example for user-supplied matrix operation class." and I discovered there was a type mismatch between the example and the inline method called perform_op in Spectra/MatOp/internal/ArnoldiOp.h. The example uses double* and ArnoldiOp.h uses const double*, so I changed all const double* to double* in ArnoldiOp.h and it compiled and ran correctly. I am unsure which implementations was the author's original intent.

**Comment by yixuan** [comment]
Hi @linuxfreebird, thanks for pointing out. Your finding is correct, but the problem is actually in the example. The `x_in` argument should be `const double*`, since the input is not meant to be modified. The examples are pretty old and I forgot to change accordingly. Now they have been [fixed](https://github.com/yixuan/spectra/commit/63fb6b5b3f6b39a2802f966310c705535d850049). Thank you.
