### ISSUE TITLE
How to compute eigenvectors simutaneously

### ISSUE THREAD

**Issue by maiwending** [yixuan/spectra#7]
Hi, Yixuan

Your code is great and very helpful.
I need to solve eigenvalue and eigenvectors simutaneously. While I believe Spectra could do this, I fail to find the explicit way in given examples.

2nd question is I test your example2 but larger scale like 1000*1000 sparse matrix.
The computation time takes much longer than Armadillo's. Is there any thing I miss?

```
#include <Eigen/Core>
#include <Eigen/SparseCore>
#include <GenEigsSolver.h>
#include <MatOp/SparseGenMatProd.h>
#include <iostream>

using namespace Spectra;

int main()
{
	// A band matrix with 1 on the main diagonal, 2 on the below-main subdiagonal,
	// and 3 on the above-main subdiagonal
	const int n =  1000;
	Eigen::SparseMatrix<double> M(n,n);
	M.reserve(Eigen::VectorXi::Constant(n, 3));
	for (int i = 0; i < n; i++)
	{
		M.insert(i, i) = 1.0;
		if (i > 0)
			M.insert(i - 1, i) = 3.0;
		if (i < n - 1)
		M.insert(i + 1, i) = 2.0;
	}
	//M = A + A.transpose();

	// Construct matrix operation object using the wrapper class SparseGenMatProd
	SparseGenMatProd<double> op(M);

	// Construct eigen solver object, requesting the largest three eigenvalues
	GenEigsSolver< double, LARGEST_MAGN, SparseGenMatProd<double> > eigs(&op,  800, 850);

	// Initialize and compute
	eigs.init();
	int nconv = eigs.compute();

	// Retrieve results
	Eigen::VectorXcd evalues;
	if (eigs.info() == SUCCESSFUL)
		evalues = eigs.eigenvalues();

	std::cout << "Eigenvalues found:\n" << evalues << std::endl;
	system("pause");
	return 0;
}

```

Would you pls help?
Thank you.

**Comment by yixuan** [comment]
Hi Wending,

For your first question, calculating eigenvalues and eigenvectors are independent, so you just need to call member function `eigenvalues()` followed by `eigenvectors()`.

For the second, could you show me your Armadillo code as well?

**Comment by maiwending** [comment]
Hi Yixuan,

Thank you for your prompt answering. My Armadillo code as below, noted it does not include ARPACK lib, but Armadillo self. My intend is to use Eign based lib, for Armadillo seems inactive for some time. I would be much appreciated if this efficiency concern is solved.
Thank you.
`#include <iostream>
#include <armadillo>

using namespace std;
using namespace arma;

// Armadillo documentation is available at:
// http://arma.sourceforge.net/docs.html

int
main(int argc, char** argv)
  {
sp_mat A(sprandu<sp_mat>(1000, 1000, 0.1));
cx_vec eigval1;
cx_vec eigval2;
cx_mat eigvec;

eigs_gen(eigval1, eigvec, A, 800);  
eigval1.print("eigval1:");

  system("pause");
  
  return 0;
  }`

**Comment by yixuan** [comment]
OK. There are two major problems here:

1. You are using two different matrices to compare with each other, so it is not a fair comparison. Different matrices have different convergence speed, and actually when `eigs_gen()` is used without ARPACK, it has almost the same code as Spectra (it was added since Armadillo 7.1000, written by me).
2. You are requesting too many eigenvalues compared with the dimension of matrix. Usually Spectra or `eigs_gen()` should be used when `k << n`, while in your case `k = 800` and `n = 1000`. With this scale, it may be faster to compute the whole spectrum using functions such as `eig_gen()` in Armadillo or `EigenSolver` in Eigen.

**Comment by maiwending** [comment]
Hi Yixuan

Thank you. 
I have made some quick test based on your suggestion. It truely improves.

My last question is:
My real project require me to compute k varys from `1/100*n` to n. Would you give me a suggestion, that at what point of `k/n` should I adopt Arnoldi algorithm or direct method, roughly?

Thank you.

**Comment by yixuan** [comment]
Ah, yes. `eigs_gen()` is more memory efficient than `eig_gen()` since it only calculates the matrix multiplication. But when you really want to calculate a large number of eigenvalues, it can also be very slow. This is a trade-off.

The threshold of `k/n` is rather problem-dependent. You may want to do some profiling on your data. Personally I would let `k/n` be no more than 1/3, and set `ncv` roughly twice of `k`.

**Comment by maiwending** [comment]
OK. 
Thank you very much, Yixuan.
You have fully clearify my concern. 
I believe this issue could be closed.
