### ISSUE TITLE
Successive calculation of eigenvalues

### ISSUE THREAD

**Issue by GPMueller** [yixuan/spectra#9]
I could not figure out how to do this efficiently: If the first eigenvalue (in general the first few) I calculated does not satisfy an additional criteria, I need to repeatedly calculate the next one until I find one that satisfies my conditions.
Example: Calculate the lowest (magnitude) eigenvalue above a certain threshold.
It would be a great waste of time to init and compute successively for 1, 2, 3, ..., n eigenvalues.

Is this what the init(const Scalar * init_resid) is meant for?
Is there any other way to use the already calculated values etc. in the next iteration?

**Comment by yixuan** [comment]
`init()` is not related to your question. It is used to initialize the solver since it is an iterative algorithm and needs a starting vector.

There is a quick solution to the example question you gave. Assuming your threshold `t` is positive, you are actually looking for the smallest eigenvalue that is greater than `t`. Then you can use a `SymEigsShiftSolver` combined with a `LARGEST_ALGE` selection rule and the parameter `sigma = t`. You may want to take a look at the documentation of the [**shift-and-invert mode**](http://yixuan.cos.name/spectra/doc/classSpectra_1_1SymEigsShiftSolver.html).

**Comment by GPMueller** [comment]
Thanks for the tip! I had misunderstood the shift and invert mode. That will be sufficient for my application.
